# install.packages(c("tidyverse","effectsize", "esc", "ReplicationSuccess", "DescTools", "kableExtra")) 

library(tidyverse)
library(plyr)
library(esc)
library(effectsize)
library(ReplicationSuccess)
library(DescTools)
library(kableExtra)
library(ggbeeswarm)


library(furrr)
library(future)
library(foreach)
library(doParallel)
library(gtable)
library(grid)
library(gridExtra)
library(ggpubr)
library(ggpattern)
library(ggtext)

# library(osfr)
# library(pwr)
library(effsize)
library(data.table)
library(compute.es)
# library(svglite)
# library(bookdown)
# library(knitr)
# library(cowplot)
# library(gridExtra)
# library(ggpubr)
# library(ggforce)
